select id, INSTITUTION_ID, FROMINSTITUTION_ID, FROMUSER_ID, TOUSER_ID, TOINSTITUTION_ID, HISTORYTYPE from DOCUMENTHISTORY where HISTORYTYPE='Letter_Copy_or_Forward' order by id desc limit 100;
select id, INSTITUTION_ID, FROMINSTITUTION_ID, FROMUSER_ID, TOUSER_ID, TOINSTITUTION_ID, HISTORYTYPE from DOCUMENTHISTORY where DOCUMENT_ID = 1317331;
select * from DOCUMENT where id =1304263;
select id, INSTITUTION_ID, DOCUMENT_ID from DOCUMENTHISTORY where INSTITUTION_ID is null;